name: 'sparql-validator'
description: 'validates & run a SPARQL file'

inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true 

outputs:
  querry_output:
    description: 'this is the output of the querrys performed by the input file'

runs:
  using: 'node16'
  main: 'index.js'