name: pipeline
on:   
  pull_request:
    branches:    
      - main

jobs:
  changedfiles:
      runs-on: ubuntu-latest
      
      outputs:
        all: ${{ steps.changes.outputs.all}}
        ts: ${{ steps.changes.outputs.ts }}
      steps:
          
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Get changed files
          id: changes
          
          run: |
            echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
            echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    needs: changedfiles
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get the output time
        run: echo "The time was ${{ steps.sparql-validator.outputs.time }}"

      - name: Changed files
        run: echo ${{needs.changedfiles.outputs.ts}}
      
      - name: sparql-validator
        uses: ./
        id: 'sparql-validator'
        with:
          files: ${{needs.changedfiles.outputs.all}}