name: pipeline
on:   
  pull_request:
    branches:    
      - main

jobs:    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    steps:

      - run: npm i follow-redirects

      - run: npm i fs
      
      - name: checkout
        uses: actions/checkout@v2
      
      - name: sparql-validator
        uses: ./
        id: 'sparql-validator'
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          graph_uri: 'http://dbpedia.org'
          format: 'application/json'
          path: 'None'

      - name: update files and push to branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Output ${{ github.actor }} - ${{ github.event.number }}" --allow-empty
          git push origin HEAD:${{ github.head_ref }} --force