name: pipeline
on: [push]

jobs:
  changedfiles:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        all: ${{ steps.changes.outputs.all}}
        ts: ${{ steps.changes.outputs.ts }}
      steps:
          # Make sure we have some code to diff.
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Get changed files
          id: changes
          # Set outputs using the command.
          run: |
            echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
            echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    needs: changedfiles
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: sparql-validator
        uses: ./ # Uses an action in the root directory
        id: 'sparql-validator'
        with:
          files: ${{needs.changedfiles.outputs.ts}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.sparql-validator.outputs.time }}"