name: pipeline
on:   
  pull_request:
    branches:    
      - main

jobs:    
  validate:
    runs-on: ubuntu-latest
    name: test pipeline
    steps:

      - run: npm i follow-redirects

      - run: npm i fs
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: sparql-validator
        uses: ./
        id: 'sparql-validator'
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          graph_uri: 'http://dbpedia.org'
          format: 'application/json'
          path: 'SPARQL-Validator'
      
      - run: ls
      - run: ls ./SPARQL-Validator
